2023-02-17 19:40:43,643 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:40:46,253 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000019B07DC23E0> files=None request_timeout=300 current_try=1
2023-02-17 19:40:46,253 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:40:52,807 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019B07DC2A10> files=None request_timeout=300 current_try=1
2023-02-17 19:40:52,808 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:40:52,894 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:40:52,905 CRITICAL [main.py:38] Unexpected error [main.py:31]: OperationalError: no such column: date
2023-02-17 19:41:12,973 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019B07DC2410> files=None request_timeout=300 current_try=1
2023-02-17 19:41:33,055 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019B07DC3730> files=None request_timeout=300 current_try=1
2023-02-17 19:41:42,898 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:41:47,710 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:41:47,971 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001D5B3798280> files=None request_timeout=300 current_try=1
2023-02-17 19:41:47,971 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:41:51,647 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001D5B37982B0> files=None request_timeout=300 current_try=1
2023-02-17 19:41:51,649 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:41:54,581 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:42:00,200 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:42:26,458 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:42:26,719 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000026DC17D4370> files=None request_timeout=300 current_try=1
2023-02-17 19:42:26,719 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:42:26,807 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000026DC17D43A0> files=None request_timeout=300 current_try=1
2023-02-17 19:42:26,808 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:42:27,977 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:42:58,282 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000026DC17D4850> files=None request_timeout=300 current_try=1
2023-02-17 19:43:04,437 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:43:40,932 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:43:41,293 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x00000220ABB042B0> files=None request_timeout=300 current_try=1
2023-02-17 19:43:41,293 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:43:46,691 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000220ABB042E0> files=None request_timeout=300 current_try=1
2023-02-17 19:43:46,693 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:43:50,644 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:44:22,229 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000220ABB04790> files=None request_timeout=300 current_try=1
2023-02-17 19:44:25,558 CRITICAL [main.py:38] Unexpected error [main.py:31]: OperationalError: no such column: date
2023-02-17 19:44:38,803 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:44:44,715 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:44:46,001 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001D5C89702E0> files=None request_timeout=300 current_try=1
2023-02-17 19:44:46,001 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:44:50,107 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001D5C8970310> files=None request_timeout=300 current_try=1
2023-02-17 19:44:50,111 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:44:50,120 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:45:12,825 ERROR    [async_telebot.py:543] no such column: date
2023-02-17 19:45:12,847 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 31, in handler
    user_data = await get_conversation_data(message.chat.id)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\src\conversationdata.py", line 15, in get_conversation_data
    await cursor.execute(f"SELECT conversation_state FROM {sqlite_db_users_conversation} "
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\core.py", line 137, in _execute
    return await future
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
sqlite3.OperationalError: no such column: date

2023-02-17 19:45:12,848 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001D5C89707C0> files=None request_timeout=300 current_try=1
2023-02-17 19:45:32,932 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001D5C8CD7580> files=None request_timeout=300 current_try=1
2023-02-17 19:45:53,018 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001D5C8CD7580> files=None request_timeout=300 current_try=1
2023-02-17 19:45:55,865 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:46:01,218 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:46:01,506 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001F95DEB8220> files=None request_timeout=300 current_try=1
2023-02-17 19:46:01,506 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:46:04,167 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F95DEB8250> files=None request_timeout=300 current_try=1
2023-02-17 19:46:04,169 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:46:04,176 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:46:04,181 ERROR    [async_telebot.py:543] no such column: date
2023-02-17 19:46:04,182 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 31, in handler
    user_data = await get_conversation_data(message.chat.id)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\src\conversationdata.py", line 18, in get_conversation_data
    await cursor.execute(query)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\core.py", line 137, in _execute
    return await future
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
sqlite3.OperationalError: no such column: date

2023-02-17 19:46:16,164 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:46:27,436 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:46:27,712 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002AC5E54C280> files=None request_timeout=300 current_try=1
2023-02-17 19:46:27,712 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:46:40,819 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002AC5E54C2B0> files=None request_timeout=300 current_try=1
2023-02-17 19:46:40,822 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:46:40,829 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:46:40,847 ERROR    [async_telebot.py:543] 'coroutine' object is not subscriptable
2023-02-17 19:46:40,847 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 31, in handler
    user_data = await get_conversation_data(message.chat.id)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\src\conversationdata.py", line 19, in get_conversation_data
    conversation_state = await cursor.fetchone()[0]
TypeError: 'coroutine' object is not subscriptable

2023-02-17 19:46:52,243 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:47:00,323 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:47:00,641 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002365870C1F0> files=None request_timeout=300 current_try=1
2023-02-17 19:47:00,642 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:47:02,444 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002365870C220> files=None request_timeout=300 current_try=1
2023-02-17 19:47:02,446 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:47:02,455 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:47:16,850 ERROR    [async_telebot.py:543] 'coroutine' object is not subscriptable
2023-02-17 19:47:16,851 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 31, in handler
    user_data = await get_conversation_data(message.chat.id)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\src\conversationdata.py", line 19, in get_conversation_data
    conversation_state = await cursor.fetchone()[0]
TypeError: 'coroutine' object is not subscriptable

2023-02-17 19:47:22,532 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002365870C6D0> files=None request_timeout=300 current_try=1
2023-02-17 19:47:27,534 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:47:30,214 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:47:30,478 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001B457DD0160> files=None request_timeout=300 current_try=1
2023-02-17 19:47:30,479 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:47:31,837 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001B457DD0190> files=None request_timeout=300 current_try=1
2023-02-17 19:47:31,839 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:47:31,848 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:47:38,812 ERROR    [async_telebot.py:543] 'NoneType' object is not subscriptable
2023-02-17 19:47:38,812 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 31, in handler
    user_data = await get_conversation_data(message.chat.id)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\src\conversationdata.py", line 19, in get_conversation_data
    conversation_state = (await cursor.fetchone())[0]
TypeError: 'NoneType' object is not subscriptable

2023-02-17 19:47:51,927 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001B457DD0640> files=None request_timeout=300 current_try=1
2023-02-17 19:48:12,008 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001B4580EB970> files=None request_timeout=300 current_try=1
2023-02-17 19:48:22,397 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:48:27,517 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:48:27,780 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002D127E88280> files=None request_timeout=300 current_try=1
2023-02-17 19:48:27,781 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:48:40,520 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002D127E882B0> files=None request_timeout=300 current_try=1
2023-02-17 19:48:40,522 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:48:40,531 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:48:47,179 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:49:16,062 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:49:16,347 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001E6473AC220> files=None request_timeout=300 current_try=1
2023-02-17 19:49:16,348 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:49:16,836 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001E6473AC250> files=None request_timeout=300 current_try=1
2023-02-17 19:49:16,840 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:49:16,846 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:49:21,591 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:49:26,362 ERROR    [async_telebot.py:543] 'list' object has no attribute 'to_dict'
2023-02-17 19:49:26,364 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 89, in reply_start
    markup = reply_markup([ENTER_WEIGHT_BUTTON])
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 73, in reply_markup
    markup.row(*buttons)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\types.py", line 2208, in row
    return self.add(*args, row_width=self.max_row_keys)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\types.py", line 2190, in add
    button_array.append(button.to_dict())
AttributeError: 'list' object has no attribute 'to_dict'

2023-02-17 19:49:36,926 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001E6473AC700> files=None request_timeout=300 current_try=1
2023-02-17 19:49:47,364 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:49:50,542 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:49:50,914 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x00000229CE7A8280> files=None request_timeout=300 current_try=1
2023-02-17 19:49:50,914 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:49:51,307 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000229CE7A82B0> files=None request_timeout=300 current_try=1
2023-02-17 19:49:51,310 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:49:51,321 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:49:53,423 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:50:00,888 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:50:37,592 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:50:37,859 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001751EAC82B0> files=None request_timeout=300 current_try=1
2023-02-17 19:50:37,859 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:50:38,164 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001751EAC82E0> files=None request_timeout=300 current_try=1
2023-02-17 19:50:38,166 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:50:38,173 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:50:44,617 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:50:50,221 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:51:11,030 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:51:11,311 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001B821638280> files=None request_timeout=300 current_try=1
2023-02-17 19:51:11,311 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:51:13,960 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001B8216382B0> files=None request_timeout=300 current_try=1
2023-02-17 19:51:13,963 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:51:13,981 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:51:13,987 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:51:20,503 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001B8219DBAC0> files=None request_timeout=300 current_try=1
2023-02-17 19:51:20,503 ERROR    [async_telebot.py:543] A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233
2023-02-17 19:51:20,510 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 91, in reply_start
    await bot.send_message(message.chat.id, text, reply_markup=markup, parse_mode="markdown")
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 99, in _process_request
    raise e
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 95, in _process_request
    json_result = await _check_result(url, resp)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 272, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.asyncio_helper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233

2023-02-17 19:51:34,059 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001B821638760> files=None request_timeout=300 current_try=1
2023-02-17 19:51:54,138 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001B82197FAF0> files=None request_timeout=300 current_try=1
2023-02-17 19:52:08,888 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:52:10,275 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:52:10,538 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x00000242D3041870> files=None request_timeout=300 current_try=1
2023-02-17 19:52:10,538 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:52:11,072 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000242D30426B0> files=None request_timeout=300 current_try=1
2023-02-17 19:52:11,073 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:52:11,078 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:52:11,082 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:52:11,318 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x00000242D30421D0> files=None request_timeout=300 current_try=1
2023-02-17 19:52:11,319 ERROR    [async_telebot.py:543] A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233
2023-02-17 19:52:11,321 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 91, in reply_start
    await bot.send_message(message.chat.id, text, reply_markup=markup, parse_mode="markdown")
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 99, in _process_request
    raise e
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 95, in _process_request
    json_result = await _check_result(url, resp)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 272, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.asyncio_helper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233

2023-02-17 19:52:31,161 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000242D30418A0> files=None request_timeout=300 current_try=1
2023-02-17 19:52:50,536 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:52:53,970 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:52:54,213 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001ABF2AD1720> files=None request_timeout=300 current_try=1
2023-02-17 19:52:54,214 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:52:56,928 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ABF2AD2560> files=None request_timeout=300 current_try=1
2023-02-17 19:52:56,929 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:52:56,934 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:52:56,939 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:52:57,199 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001ABF2AD2080> files=None request_timeout=300 current_try=1
2023-02-17 19:53:17,012 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ABF2AD1750> files=None request_timeout=300 current_try=1
2023-02-17 19:53:24,490 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:53:26,129 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:53:26,387 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000019397661840> files=None request_timeout=300 current_try=1
2023-02-17 19:53:26,387 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:53:29,425 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019397662680> files=None request_timeout=300 current_try=1
2023-02-17 19:53:29,427 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:53:29,432 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:53:29,434 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:53:29,708 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x00000193976621A0> files=None request_timeout=300 current_try=1
2023-02-17 19:53:29,708 ERROR    [async_telebot.py:543] A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233
2023-02-17 19:53:29,709 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 91, in reply_start
    await bot.send_message(message.chat.id, text, reply_markup=markup, parse_mode="markdown")
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 99, in _process_request
    raise e
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 95, in _process_request
    json_result = await _check_result(url, resp)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 272, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.asyncio_helper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233

2023-02-17 19:53:44,056 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:53:45,365 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:53:45,621 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002C812121900> files=None request_timeout=300 current_try=1
2023-02-17 19:53:45,625 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:53:45,733 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002C812122740> files=None request_timeout=300 current_try=1
2023-02-17 19:53:45,737 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:53:45,746 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:53:45,751 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:53:46,014 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002C812122260> files=None request_timeout=300 current_try=1
2023-02-17 19:53:46,015 ERROR    [async_telebot.py:543] A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233
2023-02-17 19:53:46,015 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 91, in reply_start
    await bot.send_message(message.chat.id, text, parse_mode="markdown")
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 99, in _process_request
    raise e
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 95, in _process_request
    json_result = await _check_result(url, resp)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 272, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.asyncio_helper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 233

2023-02-17 19:54:05,841 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002C812121930> files=None request_timeout=300 current_try=1
2023-02-17 19:54:25,923 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002C812121C00> files=None request_timeout=300 current_try=1
2023-02-17 19:54:46,007 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002C812122650> files=None request_timeout=300 current_try=1
2023-02-17 19:55:04,270 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:55:07,563 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:55:07,815 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002BAD08A18A0> files=None request_timeout=300 current_try=1
2023-02-17 19:55:07,815 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:55:09,669 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002BAD08A26E0> files=None request_timeout=300 current_try=1
2023-02-17 19:55:09,669 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:55:09,674 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:55:09,676 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:55:10,027 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002BAD08A2200> files=None request_timeout=300 current_try=1
2023-02-17 19:55:14,209 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:55:20,324 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:55:20,561 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001A27C261840> files=None request_timeout=300 current_try=1
2023-02-17 19:55:20,561 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:55:24,152 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001A27C262680> files=None request_timeout=300 current_try=1
2023-02-17 19:55:24,153 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:55:24,158 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:55:24,160 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:55:24,451 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001A27C2621A0> files=None request_timeout=300 current_try=1
2023-02-17 19:55:44,242 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001A27C261870> files=None request_timeout=300 current_try=1
2023-02-17 19:56:04,329 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001A27C261B40> files=None request_timeout=300 current_try=1
2023-02-17 19:56:24,412 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001A27C262590> files=None request_timeout=300 current_try=1
2023-02-17 19:56:44,494 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001A27C262B90> files=None request_timeout=300 current_try=1
2023-02-17 19:56:58,660 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:57:01,000 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:57:01,272 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001F91DC618D0> files=None request_timeout=300 current_try=1
2023-02-17 19:57:01,272 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:57:04,382 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F91DC62710> files=None request_timeout=300 current_try=1
2023-02-17 19:57:04,383 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:57:04,387 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:57:04,392 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:57:04,640 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001F91DC62230> files=None request_timeout=300 current_try=1
2023-02-17 19:57:04,640 ERROR    [async_telebot.py:543] A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 231
2023-02-17 19:57:04,641 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 91, in reply_start
    await bot.send_message(message.chat.id, text, reply_markup=markup, parse_mode="markdown")
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 99, in _process_request
    raise e
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 95, in _process_request
    json_result = await _check_result(url, resp)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 272, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.asyncio_helper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 231

2023-02-17 19:57:12,304 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:57:14,018 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:57:14,285 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000019B1EB917B0> files=None request_timeout=300 current_try=1
2023-02-17 19:57:14,286 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:57:15,712 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019B1EB925F0> files=None request_timeout=300 current_try=1
2023-02-17 19:57:15,714 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:57:15,720 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:57:15,725 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:57:16,008 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000019B1EB92110> files=None request_timeout=300 current_try=1
2023-02-17 19:57:16,008 ERROR    [async_telebot.py:543] A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
2023-02-17 19:57:16,010 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 50, in reply
    await reply_start(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 91, in reply_start
    await bot.send_message(message.chat.id, text, reply_markup=markup, parse_mode="MarkdownV2")
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 99, in _process_request
    raise e
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 95, in _process_request
    json_result = await _check_result(url, resp)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 272, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.asyncio_helper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'

2023-02-17 19:57:25,648 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:57:27,571 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:57:27,828 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000022016A918A0> files=None request_timeout=300 current_try=1
2023-02-17 19:57:27,829 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:57:28,925 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000022016A926E0> files=None request_timeout=300 current_try=1
2023-02-17 19:57:28,926 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:57:28,931 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:57:28,935 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:57:29,283 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000022016A92200> files=None request_timeout=300 current_try=1
2023-02-17 19:57:37,758 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 19:57:38,958 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 19:57:39,194 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000017D298B18D0> files=None request_timeout=300 current_try=1
2023-02-17 19:57:39,194 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 19:57:41,644 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000017D298B2710> files=None request_timeout=300 current_try=1
2023-02-17 19:57:41,645 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:57:41,650 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 19:57:41,652 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:57:41,939 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000017D298B2230> files=None request_timeout=300 current_try=1
2023-02-17 19:57:45,996 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000017D298B1900> files=None request_timeout=300 current_try=1
2023-02-17 19:57:45,998 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 19:57:46,000 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 19:57:46,002 DEBUG    [main.py:43] User data:{'conversation_state': 'init'}
2023-02-17 19:57:46,115 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000017D298B3220> files=None request_timeout=300 current_try=1
2023-02-17 19:58:06,077 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000017D298B25F0> files=None request_timeout=300 current_try=1
2023-02-17 19:58:13,378 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:09:57,630 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:09:57,953 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001ED8D432170> files=None request_timeout=300 current_try=1
2023-02-17 20:09:57,953 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:10:02,165 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ED8D432FB0> files=None request_timeout=300 current_try=1
2023-02-17 20:10:02,168 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:10:02,176 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:10:02,179 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:10:02,511 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001ED8D432EC0> files=None request_timeout=300 current_try=1
2023-02-17 20:10:04,499 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ED8D432470> files=None request_timeout=300 current_try=1
2023-02-17 20:10:04,500 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:10:04,502 INFO     [main.py:29] Message from 101610420: 75
2023-02-17 20:10:04,504 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:10:04,647 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001ED8D433280> files=None request_timeout=300 current_try=1
2023-02-17 20:10:24,584 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ED8D432E90> files=None request_timeout=300 current_try=1
2023-02-17 20:10:44,669 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ED8D432470> files=None request_timeout=300 current_try=1
2023-02-17 20:11:04,755 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ED8D432FB0> files=None request_timeout=300 current_try=1
2023-02-17 20:11:06,209 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:11:12,055 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:11:12,317 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001DAD3B6C220> files=None request_timeout=300 current_try=1
2023-02-17 20:11:12,318 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:11:16,223 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001DAD3B6C2E0> files=None request_timeout=300 current_try=1
2023-02-17 20:11:16,225 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:11:16,233 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:11:16,238 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:11:22,185 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001DAD3B6D870> files=None request_timeout=300 current_try=1
2023-02-17 20:11:37,500 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001DAD3B6C430> files=None request_timeout=300 current_try=1
2023-02-17 20:11:57,588 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001DAD3E180D0> files=None request_timeout=300 current_try=1
2023-02-17 20:11:58,216 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:12:01,972 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:12:02,274 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000026B6524C2B0> files=None request_timeout=300 current_try=1
2023-02-17 20:12:02,274 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:12:05,393 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000026B6524C2E0> files=None request_timeout=300 current_try=1
2023-02-17 20:12:05,395 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:12:05,403 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:12:05,408 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:12:09,408 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000026B6524DCC0> files=None request_timeout=300 current_try=1
2023-02-17 20:12:33,219 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000026B6524CF40> files=None request_timeout=300 current_try=1
2023-02-17 20:13:01,407 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:13:53,201 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:13:53,467 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000019FEC4482E0> files=None request_timeout=300 current_try=1
2023-02-17 20:13:53,468 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:13:57,079 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019FEC4483A0> files=None request_timeout=300 current_try=1
2023-02-17 20:13:57,081 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:13:57,090 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:13:57,096 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:14:02,334 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000019FDBB3B370> files=None request_timeout=300 current_try=1
2023-02-17 20:14:17,166 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019FEC448F70> files=None request_timeout=300 current_try=1
2023-02-17 20:14:37,249 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019FEC448F70> files=None request_timeout=300 current_try=1
2023-02-17 20:14:57,329 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019FEC448F70> files=None request_timeout=300 current_try=1
2023-02-17 20:14:58,866 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:15:06,915 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:15:07,172 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002876BC1E140> files=None request_timeout=300 current_try=1
2023-02-17 20:15:07,172 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:15:16,874 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1EF80> files=None request_timeout=300 current_try=1
2023-02-17 20:15:16,875 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:15:16,879 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 20:15:16,882 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:15:17,154 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002876BC1EAA0> files=None request_timeout=300 current_try=1
2023-02-17 20:15:25,654 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1E200> files=None request_timeout=300 current_try=1
2023-02-17 20:15:25,655 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:15:25,657 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:15:25,665 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:15:25,771 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002876BC1E440> files=None request_timeout=300 current_try=1
2023-02-17 20:15:41,555 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1EE60> files=None request_timeout=300 current_try=1
2023-02-17 20:15:41,556 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:15:41,559 INFO     [main.py:29] Message from 101610420: sdaf
2023-02-17 20:15:41,569 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:15:41,840 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002876BC1E200> files=None request_timeout=300 current_try=1
2023-02-17 20:15:43,462 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1EF20> files=None request_timeout=300 current_try=1
2023-02-17 20:15:43,463 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:15:43,465 INFO     [main.py:29] Message from 101610420: asdf
2023-02-17 20:15:43,476 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:15:43,604 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002876BC1EE60> files=None request_timeout=300 current_try=1
2023-02-17 20:15:44,944 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1F7F0> files=None request_timeout=300 current_try=1
2023-02-17 20:15:44,945 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:15:44,949 INFO     [main.py:29] Message from 101610420: 85
2023-02-17 20:15:44,963 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:15:45,085 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002876BC1FA00> files=None request_timeout=300 current_try=1
2023-02-17 20:16:05,035 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1FBE0> files=None request_timeout=300 current_try=1
2023-02-17 20:16:25,115 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1F7F0> files=None request_timeout=300 current_try=1
2023-02-17 20:16:45,192 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1FF40> files=None request_timeout=300 current_try=1
2023-02-17 20:17:05,274 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1FB80> files=None request_timeout=300 current_try=1
2023-02-17 20:17:25,356 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1FF10> files=None request_timeout=300 current_try=1
2023-02-17 20:17:45,435 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1E110> files=None request_timeout=300 current_try=1
2023-02-17 20:18:05,516 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1EEF0> files=None request_timeout=300 current_try=1
2023-02-17 20:18:25,597 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1EFB0> files=None request_timeout=300 current_try=1
2023-02-17 20:18:45,683 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1FBE0> files=None request_timeout=300 current_try=1
2023-02-17 20:19:05,760 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1FBB0> files=None request_timeout=300 current_try=1
2023-02-17 20:19:25,839 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1E440> files=None request_timeout=300 current_try=1
2023-02-17 20:19:45,917 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002876BC1E5C0> files=None request_timeout=300 current_try=1
2023-02-17 20:20:05,333 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:20:07,569 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:20:07,836 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002314B97E3E0> files=None request_timeout=300 current_try=1
2023-02-17 20:20:07,836 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:20:10,160 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314B97F220> files=None request_timeout=300 current_try=1
2023-02-17 20:20:10,161 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:20:10,167 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:20:10,174 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:20:10,510 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002314B97F130> files=None request_timeout=300 current_try=1
2023-02-17 20:20:12,452 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314B97E6E0> files=None request_timeout=300 current_try=1
2023-02-17 20:20:12,454 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:20:12,458 INFO     [main.py:29] Message from 101610420: 33
2023-02-17 20:20:12,468 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:20:13,070 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files={'photo': <_io.BufferedReader name='data/tmp/101610420_f5fd42a3.png'>} request_timeout=300 current_try=1
2023-02-17 20:20:32,539 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314B97F100> files=None request_timeout=300 current_try=1
2023-02-17 20:20:52,618 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D2CDD20> files=None request_timeout=300 current_try=1
2023-02-17 20:21:12,696 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:21:28,578 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D2CDC00> files=None request_timeout=300 current_try=1
2023-02-17 20:21:28,579 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:21:28,583 INFO     [main.py:29] Message from 101610420: sdf
2023-02-17 20:21:28,592 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:21:28,885 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002314B97F700> files=None request_timeout=300 current_try=1
2023-02-17 20:21:29,880 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D329AE0> files=None request_timeout=300 current_try=1
2023-02-17 20:21:29,881 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:21:29,885 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:21:29,893 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:21:30,019 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002314B97F7F0> files=None request_timeout=300 current_try=1
2023-02-17 20:21:30,965 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D2CDBD0> files=None request_timeout=300 current_try=1
2023-02-17 20:21:30,967 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:21:30,971 INFO     [main.py:29] Message from 101610420: 23
2023-02-17 20:21:30,980 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:21:31,430 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x000002314D329390> files={'photo': <_io.BufferedReader name='data/tmp/101610420_24bc3405.png'>} request_timeout=300 current_try=1
2023-02-17 20:21:51,052 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D329BA0> files=None request_timeout=300 current_try=1
2023-02-17 20:22:11,135 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:22:14,993 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:22:14,994 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:22:14,996 INFO     [main.py:29] Message from 101610420: sd
2023-02-17 20:22:15,005 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:22:15,319 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002314B97F100> files=None request_timeout=300 current_try=1
2023-02-17 20:22:16,149 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D329780> files=None request_timeout=300 current_try=1
2023-02-17 20:22:16,150 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:22:16,154 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:22:16,165 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:22:16,385 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002314B97F9D0> files=None request_timeout=300 current_try=1
2023-02-17 20:22:17,535 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D2CDD20> files=None request_timeout=300 current_try=1
2023-02-17 20:22:17,536 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:22:17,538 INFO     [main.py:29] Message from 101610420: 100
2023-02-17 20:22:17,547 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:22:17,910 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x000002314D329450> files={'photo': <_io.BufferedReader name='data/tmp/101610420_1d390b28.png'>} request_timeout=300 current_try=1
2023-02-17 20:22:37,616 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314D3293C0> files=None request_timeout=300 current_try=1
2023-02-17 20:22:57,695 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:23:17,774 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:23:37,857 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:23:57,941 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002314BB40790> files=None request_timeout=300 current_try=1
2023-02-17 20:24:06,536 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:24:08,422 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:24:08,692 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x0000019D880AE3E0> files=None request_timeout=300 current_try=1
2023-02-17 20:24:08,692 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:24:13,701 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AF220> files=None request_timeout=300 current_try=1
2023-02-17 20:24:13,702 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:24:13,708 INFO     [main.py:29] Message from 101610420: /enter_weight
2023-02-17 20:24:13,716 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:24:14,026 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000019D880AED40> files=None request_timeout=300 current_try=1
2023-02-17 20:24:14,894 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AE4A0> files=None request_timeout=300 current_try=1
2023-02-17 20:24:14,895 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:24:14,899 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:24:14,910 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:24:15,087 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000019D880AE6E0> files=None request_timeout=300 current_try=1
2023-02-17 20:24:16,739 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AF100> files=None request_timeout=300 current_try=1
2023-02-17 20:24:16,741 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:24:16,745 INFO     [main.py:29] Message from 101610420: 45
2023-02-17 20:24:16,752 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:24:17,347 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x0000019D880AFAC0> files={'photo': <_io.BufferedReader name='data/tmp/101610420_19b655fa.png'>} request_timeout=300 current_try=1
2023-02-17 20:24:22,124 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AF1C0> files=None request_timeout=300 current_try=1
2023-02-17 20:24:22,126 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:24:22,128 INFO     [main.py:29] Message from 101610420: /enter_weight
2023-02-17 20:24:22,138 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:24:22,256 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000019D8BA008E0> files=None request_timeout=300 current_try=1
2023-02-17 20:24:23,043 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AFA90> files=None request_timeout=300 current_try=1
2023-02-17 20:24:23,044 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:24:23,048 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:24:23,056 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:24:23,182 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000019D880AE3B0> files=None request_timeout=300 current_try=1
2023-02-17 20:24:25,142 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AFE50> files=None request_timeout=300 current_try=1
2023-02-17 20:24:25,143 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:24:25,147 INFO     [main.py:29] Message from 101610420: 865
2023-02-17 20:24:25,157 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:24:25,604 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x0000019D880AFA90> files={'photo': <_io.BufferedReader name='data/tmp/101610420_12813469.png'>} request_timeout=300 current_try=1
2023-02-17 20:24:45,231 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D880AFDF0> files=None request_timeout=300 current_try=1
2023-02-17 20:25:05,316 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7B9D0> files=None request_timeout=300 current_try=1
2023-02-17 20:25:25,410 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA79F30> files=None request_timeout=300 current_try=1
2023-02-17 20:25:45,503 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7BA90> files=None request_timeout=300 current_try=1
2023-02-17 20:26:05,627 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7BD90> files=None request_timeout=300 current_try=1
2023-02-17 20:26:25,735 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA79EA0> files=None request_timeout=300 current_try=1
2023-02-17 20:26:45,819 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7BA90> files=None request_timeout=300 current_try=1
2023-02-17 20:27:05,900 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7AE00> files=None request_timeout=300 current_try=1
2023-02-17 20:27:25,983 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA799C0> files=None request_timeout=300 current_try=1
2023-02-17 20:27:46,067 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7BBB0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:06,151 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000019D8BA7BD90> files=None request_timeout=300 current_try=1
2023-02-17 20:28:09,434 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:28:11,719 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:28:11,970 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002D620CEE410> files=None request_timeout=300 current_try=1
2023-02-17 20:28:11,970 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:28:13,562 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002D620CEF250> files=None request_timeout=300 current_try=1
2023-02-17 20:28:13,563 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:13,567 INFO     [main.py:29] Message from 101610420: /enter_weight
2023-02-17 20:28:13,576 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:28:13,840 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002D620CEED70> files=None request_timeout=300 current_try=1
2023-02-17 20:28:14,706 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002D620CEE4D0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:14,708 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:14,710 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:28:14,723 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:28:14,829 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002D620CEE710> files=None request_timeout=300 current_try=1
2023-02-17 20:28:16,177 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002D620CEF130> files=None request_timeout=300 current_try=1
2023-02-17 20:28:16,178 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:16,179 INFO     [main.py:29] Message from 101610420: sfdasf
2023-02-17 20:28:16,189 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:28:16,312 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002D620CEE4D0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:17,403 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002D620CEF1F0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:17,406 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:17,411 INFO     [main.py:29] Message from 101610420: 43
2023-02-17 20:28:17,420 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:28:17,987 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x000002D624680C70> files={'photo': <_io.BufferedReader name='data/tmp/101610420_52c0377c.png'>} request_timeout=300 current_try=1
2023-02-17 20:28:26,310 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:28:28,155 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:28:28,416 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001ECF3DFE380> files=None request_timeout=300 current_try=1
2023-02-17 20:28:28,416 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:28:30,838 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF1C0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:30,841 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:30,852 INFO     [main.py:29] Message from 101610420: 234
2023-02-17 20:28:30,861 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:28:31,173 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001ECF3DFECE0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:31,894 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFE680> files=None request_timeout=300 current_try=1
2023-02-17 20:28:31,895 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:31,898 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:28:31,915 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:28:32,117 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF1C0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:32,254 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF0A0> files=None request_timeout=300 current_try=1
2023-02-17 20:28:32,255 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:28:32,256 INFO     [main.py:29] Message from 101610420: 2134
2023-02-17 20:28:32,265 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:28:32,996 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFA30> files={'photo': <_io.BufferedReader name='data/tmp/101610420_ccdb87fe.png'>} request_timeout=300 current_try=1
2023-02-17 20:28:52,348 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF160> files=None request_timeout=300 current_try=1
2023-02-17 20:29:12,443 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF0A0> files=None request_timeout=300 current_try=1
2023-02-17 20:29:32,542 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFDF0> files=None request_timeout=300 current_try=1
2023-02-17 20:29:52,633 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFC40> files=None request_timeout=300 current_try=1
2023-02-17 20:30:12,723 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFBE0> files=None request_timeout=300 current_try=1
2023-02-17 20:30:32,808 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF700> files=None request_timeout=300 current_try=1
2023-02-17 20:30:52,913 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF3D0> files=None request_timeout=300 current_try=1
2023-02-17 20:31:13,004 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFECB0> files=None request_timeout=300 current_try=1
2023-02-17 20:31:33,110 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF160> files=None request_timeout=300 current_try=1
2023-02-17 20:31:53,209 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFE80> files=None request_timeout=300 current_try=1
2023-02-17 20:32:13,305 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFDC0> files=None request_timeout=300 current_try=1
2023-02-17 20:32:33,393 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:32:53,478 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFFC10> files=None request_timeout=300 current_try=1
2023-02-17 20:33:13,568 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFE380> files=None request_timeout=300 current_try=1
2023-02-17 20:33:33,658 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFE7D0> files=None request_timeout=300 current_try=1
2023-02-17 20:33:53,749 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFE6E0> files=None request_timeout=300 current_try=1
2023-02-17 20:34:13,836 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001ECF3DFF0D0> files=None request_timeout=300 current_try=1
2023-02-17 20:34:17,386 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:34:20,081 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:34:20,348 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x00000251C17BE9B0> files=None request_timeout=300 current_try=1
2023-02-17 20:34:20,348 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:34:24,577 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C17BF7F0> files=None request_timeout=300 current_try=1
2023-02-17 20:34:24,578 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:34:24,582 INFO     [main.py:29] Message from 101610420: /enter_weight
2023-02-17 20:34:24,590 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:34:24,895 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x00000251C17BF700> files=None request_timeout=300 current_try=1
2023-02-17 20:34:28,474 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C17BEA70> files=None request_timeout=300 current_try=1
2023-02-17 20:34:28,475 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:34:28,477 INFO     [main.py:29] Message from 101610420: 100
2023-02-17 20:34:28,486 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:34:29,080 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x00000251C5071540> files={'photo': <_io.BufferedReader name='data/tmp/101610420_9fc6299d.png'>} request_timeout=300 current_try=1
2023-02-17 20:34:44,093 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C17BF6D0> files=None request_timeout=300 current_try=1
2023-02-17 20:34:44,094 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:34:44,096 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:34:44,107 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:34:44,399 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x00000251C5073820> files=None request_timeout=300 current_try=1
2023-02-17 20:34:46,160 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C5071A50> files=None request_timeout=300 current_try=1
2023-02-17 20:34:46,160 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:34:46,163 INFO     [main.py:29] Message from 101610420: 10
2023-02-17 20:34:46,172 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:34:46,646 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x00000251C19A4130> files={'photo': <_io.BufferedReader name='data/tmp/101610420_fd107a17.png'>} request_timeout=300 current_try=1
2023-02-17 20:35:06,246 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C5073CD0> files=None request_timeout=300 current_try=1
2023-02-17 20:35:26,330 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C50E9F30> files=None request_timeout=300 current_try=1
2023-02-17 20:35:46,411 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C513BE50> files=None request_timeout=300 current_try=1
2023-02-17 20:36:06,491 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C19A4610> files=None request_timeout=300 current_try=1
2023-02-17 20:36:26,573 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000251C19A4640> files=None request_timeout=300 current_try=1
2023-02-17 20:36:43,005 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:36:44,494 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:36:44,749 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001641296EB60> files=None request_timeout=300 current_try=1
2023-02-17 20:36:44,750 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:36:44,834 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001641296F9A0> files=None request_timeout=300 current_try=1
2023-02-17 20:36:44,835 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:36:44,842 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:36:44,848 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:36:45,119 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001641296F8B0> files=None request_timeout=300 current_try=1
2023-02-17 20:36:46,205 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001641296EE60> files=None request_timeout=300 current_try=1
2023-02-17 20:36:46,206 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:36:46,210 INFO     [main.py:29] Message from 101610420: 23
2023-02-17 20:36:46,217 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:36:46,846 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x0000016412B24A30> files={'photo': <_io.BufferedReader name='data/tmp/101610420_d4d70997.png'>} request_timeout=300 current_try=1
2023-02-17 20:37:06,290 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001641296F880> files=None request_timeout=300 current_try=1
2023-02-17 20:37:26,374 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000016412B24A60> files=None request_timeout=300 current_try=1
2023-02-17 20:37:46,126 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:37:48,034 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:37:48,284 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000002331684EB60> files=None request_timeout=300 current_try=1
2023-02-17 20:37:48,284 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:37:49,203 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002331684F9A0> files=None request_timeout=300 current_try=1
2023-02-17 20:37:49,206 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:37:49,214 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:37:49,223 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:37:49,599 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000002331684F8B0> files=None request_timeout=300 current_try=1
2023-02-17 20:37:50,576 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002331684EE60> files=None request_timeout=300 current_try=1
2023-02-17 20:37:50,577 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:37:50,581 INFO     [main.py:29] Message from 101610420: 11
2023-02-17 20:37:50,589 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:37:51,238 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x0000023316A64A00> files={'photo': <_io.BufferedReader name='data/tmp/101610420_bc9a42b3.png'>} request_timeout=300 current_try=1
2023-02-17 20:38:10,656 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000002331684F880> files=None request_timeout=300 current_try=1
2023-02-17 20:38:30,735 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000023316A64A30> files=None request_timeout=300 current_try=1
2023-02-17 20:38:50,815 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000023316A650F0> files=None request_timeout=300 current_try=1
2023-02-17 20:39:10,893 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000023316A643A0> files=None request_timeout=300 current_try=1
2023-02-17 20:39:22,667 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:39:24,516 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:39:24,781 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x000001F1A2FAAC50> files=None request_timeout=300 current_try=1
2023-02-17 20:39:24,783 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:39:25,931 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FABA90> files=None request_timeout=300 current_try=1
2023-02-17 20:39:25,933 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:39:25,942 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:39:25,952 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:39:26,231 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001F1A2FAB9A0> files=None request_timeout=300 current_try=1
2023-02-17 20:39:27,688 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FAAF50> files=None request_timeout=300 current_try=1
2023-02-17 20:39:27,689 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:39:27,690 INFO     [main.py:29] Message from 101610420: 100
2023-02-17 20:39:27,699 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:39:28,229 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x000001F1A6891480> files={'photo': <_io.BufferedReader name='data/tmp/101610420_dd63eab3.png'>} request_timeout=300 current_try=1
2023-02-17 20:39:47,768 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FAB970> files=None request_timeout=300 current_try=1
2023-02-17 20:40:07,849 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FAAF50> files=None request_timeout=300 current_try=1
2023-02-17 20:40:23,527 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FABCD0> files=None request_timeout=300 current_try=1
2023-02-17 20:40:23,528 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:40:23,530 INFO     [main.py:29] Message from 101610420: /help
2023-02-17 20:40:23,540 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:40:23,888 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001F1A2FABAF0> files=None request_timeout=300 current_try=1
2023-02-17 20:40:26,600 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FAAF50> files=None request_timeout=300 current_try=1
2023-02-17 20:40:26,601 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:40:26,605 INFO     [main.py:29] Message from 101610420: /start
2023-02-17 20:40:26,612 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:40:26,737 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x000001F1A6893D30> files=None request_timeout=300 current_try=1
2023-02-17 20:40:28,367 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x000001F1A2FABBB0> files=None request_timeout=300 current_try=1
2023-02-17 20:40:28,368 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:40:28,371 INFO     [main.py:29] Message from 101610420: /plot
2023-02-17 20:40:28,379 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:40:28,379 ERROR    [async_telebot.py:543] name 'reply_plot' is not defined
2023-02-17 20:40:28,379 DEBUG    [async_telebot.py:544] Exception traceback:
Traceback (most recent call last):
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 34, in handler
    await reply(message, user_data)
  File "C:\Users\clavi\PycharmProjects\bodymass_bot\main.py", line 65, in reply
    await reply_plot(message, user_data)
NameError: name 'reply_plot' is not defined

2023-02-17 20:40:31,359 WARNING  [async_telebot.py:455] Polling is stopped.
2023-02-17 20:48:59,071 WARNING  [async_telebot.py:395] Setting non_stop to False will stop polling on API and system exceptions.
2023-02-17 20:48:59,332 DEBUG    [asyncio_helper.py:93] Request: method=get url=getMe params=<aiohttp.formdata.FormData object at 0x00000273355A7910> files=None request_timeout=300 current_try=1
2023-02-17 20:48:59,333 INFO     [async_telebot.py:399] Starting your bot with username: [@bodymasstracker_bot]
2023-02-17 20:49:00,276 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000273355A7C10> files=None request_timeout=300 current_try=1
2023-02-17 20:49:00,278 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:49:00,282 INFO     [main.py:29] Message from 101610420: Enter today's body weight
2023-02-17 20:49:00,285 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:49:00,574 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x00000273355E4700> files=None request_timeout=300 current_try=1
2023-02-17 20:49:01,955 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000273355A79D0> files=None request_timeout=300 current_try=1
2023-02-17 20:49:01,955 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:49:01,959 INFO     [main.py:29] Message from 101610420: /plot
2023-02-17 20:49:01,976 DEBUG    [main.py:53] User data:{'conversation_state': 'awaiting_body_weight'}
2023-02-17 20:49:02,526 DEBUG    [asyncio_helper.py:93] Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files={'photo': <_io.BufferedReader name='data/tmp/101610420_910dea02.png'>} request_timeout=300 current_try=1
2023-02-17 20:49:21,204 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000273355A7B20> files=None request_timeout=300 current_try=1
2023-02-17 20:49:21,205 INFO     [async_telebot.py:567] Received 1 new updates
2023-02-17 20:49:21,208 INFO     [main.py:29] Message from 101610420: /help
2023-02-17 20:49:21,215 DEBUG    [main.py:53] User data:{'conversation_state': 'init'}
2023-02-17 20:49:21,514 DEBUG    [asyncio_helper.py:93] Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000027337932800> files=None request_timeout=300 current_try=1
2023-02-17 20:49:41,308 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x00000273355A7C40> files=None request_timeout=300 current_try=1
2023-02-17 20:50:01,390 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:50:21,478 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:50:41,562 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:51:01,649 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:51:21,733 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:51:41,823 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:52:01,915 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:52:22,022 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:52:42,109 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:53:02,199 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:53:22,296 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:53:42,407 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:54:02,497 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:54:22,581 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:54:42,664 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:55:03,051 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:55:23,139 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:55:43,236 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:56:03,319 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:56:23,400 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:56:43,485 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:57:03,573 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:57:23,655 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:57:43,737 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:58:03,823 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:58:23,917 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:58:44,003 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:59:04,094 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:59:24,178 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 20:59:44,269 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:00:04,357 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:00:24,444 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:00:44,842 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:01:04,923 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:01:25,009 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:01:45,090 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:02:05,177 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:02:25,265 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:02:45,352 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:03:05,437 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:03:25,521 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:03:45,617 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:04:05,705 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:04:25,795 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:04:45,905 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:05:05,990 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:05:26,081 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:05:46,171 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:06:06,254 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:06:26,344 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:06:46,429 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:07:06,520 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:07:26,609 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:07:46,696 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:08:06,779 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:08:26,875 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:08:46,965 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:09:07,049 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:09:27,140 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:09:47,226 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:10:07,312 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:10:27,397 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:10:47,495 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:11:07,579 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:11:27,668 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:11:47,754 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:12:07,840 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:12:27,927 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:12:48,011 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:13:08,093 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:13:28,180 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:13:48,267 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:14:08,356 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:14:28,445 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:14:48,531 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:15:08,618 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:15:28,699 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:15:48,786 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:16:08,870 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:16:28,956 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:16:49,062 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:17:09,155 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:17:29,243 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:17:49,331 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:18:09,418 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:18:29,501 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:18:49,592 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:19:09,673 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:19:29,753 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:19:49,837 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:20:09,924 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:20:30,012 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:20:50,096 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:21:10,183 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:21:30,270 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:21:50,544 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:22:10,630 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:22:30,718 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:22:50,806 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:23:10,891 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:23:30,976 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:23:51,060 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:24:11,148 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:24:31,232 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:24:51,316 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:25:11,403 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:25:31,487 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:25:51,573 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:26:11,656 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:26:31,741 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:26:51,827 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:27:11,914 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:27:31,998 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:27:52,084 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:28:12,171 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:28:32,257 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:28:52,342 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:29:12,425 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:29:32,510 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:29:52,596 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:30:12,714 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:30:32,801 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:30:52,890 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:31:12,975 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:31:33,061 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:31:53,147 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:32:13,232 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:32:33,316 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:32:53,399 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:33:13,485 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:33:33,569 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:33:53,654 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:34:13,738 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:34:33,822 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:34:53,908 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:35:13,993 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:35:34,089 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:35:54,184 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:36:14,273 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
2023-02-17 21:36:34,362 DEBUG    [asyncio_helper.py:93] Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000027338FDFC70> files=None request_timeout=300 current_try=1
